#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Hirofumi Saito
#SPDX-License-Identifier: MIT
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += float(line)
    except:
        ans += float(line)


print(ans)